version: '3'


services:
  mongo:
    image: mongo
    environment:
      environment:
      MONGO_INITDB_DATABASE: ApartmentProject
    ports:
      - "27017:27017"
  server:
          build: ./apatmentproject
          expose:
              - 8080
          ports:
              - 8080:8080
          volumes:
              - ./backend/src:/srv/app/admin-server/src
          depends_on:
              - mongo
          command: npm run start
  
  client:
          build: ./apartmenclientapp
          expose:
              - 3000   
          ports:
              - 3000:3000
          volumes:
              - ./frontend/src:/srv/app/admin-client/src
              - ./frontend/public:/srv/app/admin-client/public
          stdin_open: true
          command: npm run dev
